#!/bin/bash
files="$(cat ~/.trash.log | awk '/[ \/]'$1'$/')"
if [[ $files == "" ]]
then
	echo "There is no such file!"
	exit 1
fi
echo "$files" | while read line
do
	path2="$(echo $line | awk '{print $2}')"
	echo $path2
	echo "Restore file? (y/n)"
	while read -r -n1 key
	do
		if [[ $key == [yn] ]]
		then
			break;
		fi
	done </dev/tty
	if [[ $key == y ]]
	then
		echo ""
		num="$(echo $line | awk '{print $1}')"
		path1=~/.trash/$num
		ln $path1 $path2 ||
		{
			ln $path1 ~/$1 &&
			echo "The file will be restored in current user's directory!"
		} ||
		{
			echo "Write new name of restored file:"
			while true
			do
				read path </dev/tty
				{
					ln $path1 ~/$path &&
					break
				} ||
				echo "Wrong path!"
			done
		}
		rm $path1
		sed -i "/^"$num" /d" ~/.trash.log
		break
	fi
done 2>/dev/null
