#!/bin/bash
file=CPU_burst
>$file
proc="$(ps -A -F | sed '1d' | awk '{print $2}')"
for pid in $proc
do
	ppid="$(cat '/proc/'$pid'/status' | awk '/PPid/ {print $2}')"
	runtime="$(cat '/proc/'$pid'/sched' | awk '/sum_exec_runtime/ {print $3}')"
	switches="$(cat '/proc/'$pid'/sched' | awk '/nr_switches/ {print $3}')"
	art="$(echo $runtime / $switches | bc -l)"
	list="$list""
""$(echo $pid $ppid $art)"
done 2>/dev/null
list="$(echo "$list" | sort -k2 -n)"
echo "$list" | awk '$2 != "" {print "ProcessID="$1" : Parent_ProcessID="$2" : Average_Running_Time="$3}' >> $file
