#!/bin/bash
file=CPU_burst2
>$file
list="$(cat CPU_burst | sed 's/[[:alpha:]=:_]//g')"
list2=123
while read line
do
	if [[ $ppid != "$(echo $line | awk '{print $2}')" ]]
	then
		ppid="$(echo $line | awk '{print $2}')"
		sum="$(echo \\"$list\\" | awk '$2 == ppid {print $3}' ppid=$ppid | awk '{sum += $1} END {print sum}')"
		count="$(echo \\"$list\\" | awk '$2 == ppid {print $2}' ppid=$ppid | sort | uniq -c | awk '{print $1}')"
		ascp="$(echo $sum / $count | bc -l)"
	fi
	list2="$list2""
""$line"" ""$ascp"
done < <(echo "$list")
echo "$list2" | awk '{print "ProcessID="$1" : Parent_ProcessID="$2" : Average_Running_Time="$3" : Average_Sleeping_Children_of_ParentID="$2" is "$4}' >> $file
