#!/bin/bash
mkdir test &&
{
	(echo "catalog test was created successfully") >>report
	>test/"$(date +"%y-%m-%d %H-%M-%S")"
}
ping www.net_nikogo.ru || echo "$(date +"%y-%m-%d %H-%M-%S")"" error" >>report
